<?php

declare(strict_types=1);

namespace App\Discovery;

use App\Evidence\MentionValidity;

/**
 * Deterministic candidate construction for ICP determination (D-P2).
 *
 * This is the LAMP port of PI's PERSONA_KG move
 * (~/workspace/jev-icp-determination/PERSONA_KG_SPEC.md §3): candidate
 * segments for ICP determination are generated by a DETERMINISTIC TEMPLATE
 * over (archetype × buyer facts) — never by an LLM pre-draft.
 *
 * The JEV filter (Stage A) and ScoreLeadFitAction (Stage B) then JUDGE these
 * candidates; they never invent them. This class is the ONLY candidate
 * source for LAMP's discovery path: there is no model-generated pre-draft
 * to fall back to, and keeping one as a fallback would reintroduce phantoms
 * through the back door (PI spec §9, decision 10).
 *
 * Design properties (mirroring includes/Evidence/*):
 *   - Pure, DB-free, deterministic: same inputs → byte-identical outputs.
 *   - No network, no wall clock, no LLM, no JEV in the construction path.
 *   - Fail closed, never filler: absent buyer-fact fields omit their clause;
 *     a hollow intake (no product_summary) degrades to persona-only
 *     candidates with intake_hollow=1 rather than synthesized filler.
 *   - Honest absence: a seller this table does not cover (non-B2B) yields
 *     zero candidates and a machine-readable zero_reason — never padded,
 *     never papered over with generated prose.
 *
 * NEVER_JEV boundary 5 binds this class: candidate retrieval, scope
 * filtering, aggregation, thresholds, and ranking keys are deterministic
 * code. The never-invent-evidence rule binds the template: every sentence
 * is single-sourced to either a KG persona field or a verbatim buyer-fact
 * field. If a sentence cannot be traced to exactly one of those sources,
 * the template is wrong — fix the template, not the data.
 *
 * What this class deliberately does NOT do (fit judgments stay downstream):
 *   - Buyer-stated exclusions (anti-personas) are CARRIED on the buyer-facts
 *     input and passed through to the pipeline; they are NOT applied here.
 *     Exclusion enforcement is the deterministic hard-veto path inside
 *     ScoreLeadFitAction / Stage A, where an owner-hypothesis mismatch is
 *     judged as poor fit — deliberately not pre-filtered, per the PI spec
 *     §5 code-vs-JEV line: "filtering it in code would be the KG judging."
 *     [ASSUMPTION — owner can veto: apply buyer exclusions at construction
 *     time as a deterministic scope filter instead.]
 *   - It does not classify the buyer's industry, infer titles, or rank
 *     candidates by fit. Retrieval and ordering only.
 */
class CandidateBuilder
{
    /**
     * Deterministic shortlist size (PI spec §9, decision 1: M = 3).
     * [ASSUMPTION — owner can veto.]
     */
    public const MAX_CANDIDATES = 3;

    /**
     * Template version — pinned. A template change is a taxonomy release,
     * never a silent edit (PI spec §6, checklist item 12).
     */
    public const TEMPLATE_VERSION = '1.0';

    /**
     * Description cap in characters, with a truncation marker (never silent).
     */
    public const DESCRIPTION_MAX_CHARS = 800;
    public const TRUNCATION_MARKER = ' […]';

    /**
     * Buyer-facts fields the template may consume — and ONLY these.
     * Nothing else is read in the construction path.
     *
     *   product_summary    string   what is sold, founder's own words (≤2000 chars)
     *   price_band         ?string  e.g. '$50–500/mo'
     *   transaction        ?string  delivery mode, e.g. 'ongoing digital subscription'
     *   geography_scale    ?string  one of the shared scope ladder
     *   geography_named    ?string  e.g. 'US, UK, Canada'
     *   size_band          ?string  buyer-stated target company size, e.g. '20–500 employees'
     *   target_titles      array    buyer-stated target titles/roles
     *   buyer_line         ?string  free-text buyer line, quoted verbatim
     *   owner_hypothesis   ?array   ['audience' => string], quoted verbatim (≤400 chars)
     *   sells_to_businesses bool    false => this table does not apply (honest absence)
     *   exclusions         array    buyer-stated anti-persona keywords — CARRIED, not applied
     */
    public static function construct(array $buyerFacts): array
    {
        $meta = [
            'template_version' => self::TEMPLATE_VERSION,
            'table_version' => BuyerArchetypes::TABLE_VERSION,
            'eligible_count' => 0,
            'truncated_to' => self::MAX_CANDIDATES,
            'scope_filter_applied' => false,
            'scope_widened' => false,
            'intake_hollow' => false,
            'zero_reason' => null,
        ];

        // --- Scope gate: this table is B2B-only. ---
        // A non-B2B seller gets zero candidates with a machine-readable
        // reason — asserted ignorance, never padded with prose.
        if (($buyerFacts['sells_to_businesses'] ?? true) !== true) {
            $meta['zero_reason'] = 'non_b2b_seller';
            return ['candidates' => [], 'meta' => $meta];
        }

        $productSummary = self::cleanStr($buyerFacts['product_summary'] ?? null);
        $meta['intake_hollow'] = ($productSummary === null);

        // --- Eligibility: active archetypes passing the scope-match rule. ---
        // Scope-match (PI spec §3.1): ladder(archetype.scope_default) >=
        // ladder(buyer geography_scale). A missing or unknown buyer scale
        // WIDENS the hypothesis space (discovery spec §1: the loop never
        // blocks on missing intake) — it never narrows it.
        $buyerScale = self::cleanStr($buyerFacts['geography_scale'] ?? null);
        $buyerLevel = self::scopeLevel($buyerScale);
        $meta['scope_filter_applied'] = ($buyerLevel !== null);
        $meta['scope_widened'] = ($buyerLevel === null);

        $eligible = [];
        foreach (BuyerArchetypes::active() as $archetype) {
            $personaLevel = self::scopeLevel($archetype['scope_default'] ?? null);
            if ($personaLevel === null) {
                continue; // archetype with an unknown scope can never pass — fail closed.
            }
            if ($buyerLevel !== null && $personaLevel < $buyerLevel) {
                continue; // scope does not cover the buyer.
            }
            $eligible[] = $archetype;
        }
        $meta['eligible_count'] = count($eligible);

        // --- Expansion order (total, deterministic): ---
        // (1) eligible primaries, persona_id ASC; (2) eligible secondaries,
        // persona_id ASC. Truncate to MAX_CANDIDATES. Fewer eligible than M
        // → fewer candidates (never padded). Zero → zero candidates.
        $order = static function (array $a, array $b): int {
            $sa = ($a['strength'] ?? '') === BuyerArchetypes::STRENGTH_SECONDARY ? 1 : 0;
            $sb = ($b['strength'] ?? '') === BuyerArchetypes::STRENGTH_SECONDARY ? 1 : 0;
            if ($sa !== $sb) {
                return $sa <=> $sb;
            }
            return strcmp((string)$a['id'], (string)$b['id']);
        };
        usort($eligible, $order);
        $selected = array_slice($eligible, 0, self::MAX_CANDIDATES);

        // --- Template interpolation (verbatim fields only). ---
        $candidates = [];
        foreach ($selected as $i => $archetype) {
            $candidates[] = [
                'segment_id' => 'seg_' . $archetype['id'],
                'persona_id' => $archetype['id'],
                'description' => self::renderDescription($archetype, $buyerFacts, $productSummary),
                'construction_order' => $i,
                'intake_hollow' => $meta['intake_hollow'] ? 1 : 0,
            ];
        }

        return ['candidates' => $candidates, 'meta' => $meta];
    }

    /**
     * The template (exact wording). Sentences:
     *   S1: "{label}: {definition}"                          (KG persona field)
     *   S2: "Typical pains: {pains_csv}."                    (KG persona field)
     *   S3: "{buying_context}"                               (KG persona field)
     *   S4 (iff product_summary): "They buy {product_summary}{price}{txn}{geo}{size}{titles}."
     *       price  = " in the {price_band} price band"        (buyer fact, verbatim)
     *       txn    = " via {transaction}"                     (buyer fact, verbatim)
     *       geo    = " serving {geography_named}"              (buyer fact, verbatim)
     *              | " at {geography_scale} scale"             (buyer fact, verbatim)
     *       size   = " for companies with {size_band}"         (buyer fact, verbatim)
     *       titles = " — buyers are {titles_csv}"             (buyer fact, verbatim)
     *   S4b (iff buyer_line): 'Their buyer line reads: "{buyer_line}".'  (verbatim quote)
     *   S5 (iff owner_hypothesis.audience): 'Owner hypothesis: "{audience}".' (verbatim quote)
     *
     * Clauses join with punctuation-level concatenation only — no added
     * adjectives, no causal claims, no inferred attributes. Absent fields
     * omit their clause; nothing is synthesized.
     */
    public static function renderDescription(array $archetype, array $buyerFacts, ?string $productSummary = null): string
    {
        $productSummary ??= self::cleanStr($buyerFacts['product_summary'] ?? null);

        $s1 = $archetype['label'] . ': ' . $archetype['definition'];
        $s2 = 'Typical pains: ' . implode(', ', $archetype['pains'] ?? []) . '.';
        $s3 = (string)($archetype['buying_context'] ?? '');

        $parts = [$s1, $s2, $s3];

        if ($productSummary !== null) {
            $s4 = 'They buy ' . $productSummary;

            $priceBand = self::cleanStr($buyerFacts['price_band'] ?? null);
            if ($priceBand !== null) {
                $s4 .= ' in the ' . $priceBand . ' price band';
            }

            $transaction = self::cleanStr($buyerFacts['transaction'] ?? null);
            if ($transaction !== null) {
                $s4 .= ' via ' . $transaction;
            }

            $geoNamed = self::cleanStr($buyerFacts['geography_named'] ?? null);
            $geoScale = self::cleanStr($buyerFacts['geography_scale'] ?? null);
            if ($geoNamed !== null) {
                $s4 .= ' serving ' . $geoNamed;
            } elseif ($geoScale !== null) {
                $s4 .= ' at ' . $geoScale . ' scale';
            }

            $sizeBand = self::cleanStr($buyerFacts['size_band'] ?? null);
            if ($sizeBand !== null) {
                $s4 .= ' for companies with ' . $sizeBand;
            }

            $titles = self::cleanTitles($buyerFacts['target_titles'] ?? null);
            if ($titles !== []) {
                $s4 .= ' — buyers are ' . implode(', ', $titles);
            }

            $parts[] = $s4 . '.';
        }

        $buyerLine = self::cleanStr($buyerFacts['buyer_line'] ?? null);
        if ($buyerLine !== null) {
            $parts[] = 'Their buyer line reads: "' . $buyerLine . '".';
        }

        $audience = null;
        $hyp = $buyerFacts['owner_hypothesis'] ?? null;
        if (is_array($hyp)) {
            $audience = self::cleanStr($hyp['audience'] ?? null, 400);
        }
        if ($audience !== null) {
            $parts[] = 'Owner hypothesis: "' . $audience . '".';
        }

        $text = implode(' ', $parts);
        return self::cap($text, self::DESCRIPTION_MAX_CHARS);
    }

    /**
     * Scope ladder level (shared ladder — no second taxonomy). Returns null
     * for missing/unknown values; the caller widens on null.
     */
    public static function scopeLevel(?string $scope): ?int
    {
        if ($scope === null) {
            return null;
        }
        $level = array_search($scope, MentionValidity::SCOPES, true);
        return $level === false ? null : (int)$level;
    }

    // ------------------------------------------------------------------
    // Internals
    // ------------------------------------------------------------------

    /**
     * Trim a string fact; null/empty/non-string → null. Optional char cap
     * (owner_hypothesis.audience is schema-capped at 400).
     */
    private static function cleanStr(mixed $value, ?int $cap = null): ?string
    {
        if (!is_string($value)) {
            return null;
        }
        $value = trim(preg_replace('/\s+/', ' ', $value) ?? '');
        if ($value === '') {
            return null;
        }
        if ($cap !== null && mb_strlen($value, 'UTF-8') > $cap) {
            $value = mb_substr($value, 0, $cap, 'UTF-8');
        }
        return $value;
    }

    /**
     * Normalize target_titles to a clean list of non-empty strings.
     */
    private static function cleanTitles(mixed $value): array
    {
        if (!is_array($value)) {
            return [];
        }
        $out = [];
        foreach ($value as $t) {
            $t = self::cleanStr($t);
            if ($t !== null) {
                $out[] = $t;
            }
        }
        return $out;
    }

    /**
     * Hard cap with an explicit truncation marker (never silent).
     */
    private static function cap(string $text, int $maxChars): string
    {
        if (mb_strlen($text, 'UTF-8') <= $maxChars) {
            return $text;
        }
        $marker = self::TRUNCATION_MARKER;
        $keep = $maxChars - mb_strlen($marker, 'UTF-8');
        return mb_substr($text, 0, max(0, $keep), 'UTF-8') . $marker;
    }
}
